# Generated by Django 5.1.3 on 2024-11-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="users",
            name="nickname",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="users",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
