# Generated by Django 5.1.3 on 2024-12-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_users_name_alter_users_nickname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
