# Generated by Django 5.1.3 on 2024-11-29 06:57

import django.db.models.deletion
from django.db import migrations, models

import constraints


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.IntegerField()),
                ("after_amount", models.IntegerField()),
                ("account_title", models.CharField(max_length=255)),
                ("dw_type", models.CharField(choices=[("DEPOSIT", "입금"), ("WITHDRAW", "출금")], max_length=10)),
                (
                    "amount_type",
                    models.CharField(
                        choices=[
                            ("ATM", "ATM 거래"),
                            ("TRANSFER", "계좌이체"),
                            ("AUTOMATIC_TRANSFER", "자동이체"),
                            ("CARD", "카드결제"),
                            ("INTEREST", "이자"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transaction_at", models.DateTimeField(auto_now_add=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="account.account")),
            ],
            options={
                "db_table": "transaction_history",
            },
            bases=(models.Model, constraints.Constraint),
        ),
    ]
